<?php

namespace Webkul\Employee\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Webkul\Security\Models\User;

class EmployeeJobPositionSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('employees_job_positions')->delete();

        $user = User::first();

        $jobPositions = [
            [
                'sort'               => 1,
                'name'               => 'Operator Produksi',
                'description'        => 'Mengoperasikan mesin produksi dan memastikan proses berjalan lancar.',
                'requirements'       => 'Pengalaman kerja di pabrik, mampu bekerja dengan shift.',
                'is_active'          => true,
                'expected_employees' => 20,
                'no_of_employee'     => 15,
                'no_of_recruitment'  => 5,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 2,
                'name'               => 'Teknisi Listrik',
                'description'        => 'Melakukan perbaikan dan perawatan instalasi listrik.',
                'requirements'       => 'Sertifikat kelistrikan, paham sistem instalasi dan panel listrik.',
                'is_active'          => true,
                'expected_employees' => 5,
                'no_of_employee'     => 3,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 3,
                'name'               => 'Sopir Truk',
                'description'        => 'Mengemudikan kendaraan besar untuk distribusi barang.',
                'requirements'       => 'SIM B1/B2, pengalaman mengemudikan truk minimal 2 tahun.',
                'is_active'          => true,
                'expected_employees' => 8,
                'no_of_employee'     => 6,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 4,
                'name'               => 'Welder (Tukang Las)',
                'description'        => 'Mengerjakan pengelasan pada bahan logam sesuai spesifikasi.',
                'requirements'       => 'Mahir las listrik/las argon, paham K3 dasar.',
                'is_active'          => true,
                'expected_employees' => 6,
                'no_of_employee'     => 4,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 5,
                'name'               => 'Mekanik',
                'description'        => 'Memperbaiki dan merawat kendaraan serta mesin produksi.',
                'requirements'       => 'Menguasai perbaikan mesin diesel dan bensin.',
                'is_active'          => true,
                'expected_employees' => 7,
                'no_of_employee'     => 5,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 6,
                'name'               => 'Petugas Gudang',
                'description'        => 'Mengatur keluar masuk barang dan menjaga stok gudang.',
                'requirements'       => 'Mampu mengangkat beban berat, teliti dalam pencatatan.',
                'is_active'          => true,
                'expected_employees' => 10,
                'no_of_employee'     => 8,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 7,
                'name'               => 'Tukang Bangunan',
                'description'        => 'Melaksanakan pekerjaan konstruksi dan renovasi.',
                'requirements'       => 'Berpengalaman di bidang konstruksi, mampu membaca gambar kerja sederhana.',
                'is_active'          => true,
                'expected_employees' => 12,
                'no_of_employee'     => 10,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 8,
                'name'               => 'Cleaning Service',
                'description'        => 'Menjaga kebersihan area kerja dan fasilitas perusahaan.',
                'requirements'       => 'Rajin, disiplin, dan memahami standar kebersihan.',
                'is_active'          => true,
                'expected_employees' => 15,
                'no_of_employee'     => 12,
                'no_of_recruitment'  => 3,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 9,
                'name'               => 'Security',
                'description'        => 'Menjaga keamanan lingkungan kerja dan aset perusahaan.',
                'requirements'       => 'Memiliki pengalaman sebagai satpam, bersertifikat Gada Pratama lebih disukai.',
                'is_active'          => true,
                'expected_employees' => 8,
                'no_of_employee'     => 6,
                'no_of_recruitment'  => 2,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'name'               => 'Supir Pribadi',
                'description'        => 'Mengemudikan kendaraan untuk keperluan operasional atau manajemen.',
                'requirements'       => 'SIM A, berpengalaman, paham rute lokal.',
                'is_active'          => true,
                'expected_employees' => 3,
                'no_of_employee'     => 2,
                'no_of_recruitment'  => 1,
                'department_id'      => null,
                'company_id'         => null,
                'creator_id'         => $user?->id,
                'employment_type_id' => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
        ];

        DB::table('employees_job_positions')->insert($jobPositions);
    }
}
